config/routes.rb
Rails.application.routes.draw do
  
  root 'application#home'

  get '/calculate' => 'properties#calculate', as: :calculate
  get '/full_list' => 'properties#full_list', as: :full_list

  get '/signup' => 'users#new', as: :signup

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout


  resources :properties
  resources :users

end

app/models/property.rb
class Property
  include Mongoid::Document
  include Mongoid::Timestamps
  field :address, type: String
  field :list_price, type: Integer
  field :sale_price, type: Integer
  field :fix_costs, type: Integer
  field :time_held, type: Integer


  # calculated fields
  field :profit_margin, type: Integer
  field :profit_percent, type: Float

  # relationals
  belongs_to :user

  # attr_accessor :sale_price, :list_price, :fix_costs, :profit_margin, :profit_percent 

  validates :list_price, :sale_price, presence: true
  
  def date_published
    created_at.localtime.strftime("%A, %B %-d, %Y at %l:%M %p")
  end 

  def calculate_profit_margin
     (self.sale_price - self.list_price - fix_costs).to_i
  end

  def calculate_profit_percent
     (self.fix_costs * 100).to_i / (self.sale_price - self.fix_costs-self.list_price)
  end

  
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword # load secure password

  has_secure_password # tell rails this model has a secure password

  field :first_name, type: String
  field :last_name, type: String
  field :username, type: String
  field :password_digest, type: String

  #relational
  has_many :properties


  validates :username, uniqueness: { case_sensitive: false } # ensure usernames are unique
  validates :password, confirmation: true # ensure password confirmation is filled out and m
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def home
    @properties = Property.all
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
    redirect_to posts_path unless current_user
  end

  def terms_of_condtions
  end

  def support
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  

  # GET /properties
  # GET /properties.json
  def full_list
    @properties = Property.all.order(sale_price: :desc)
  end

  def index 
    @properties = Property.all.order(created_at: :desc)
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    #before_action :authorize
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  def calculate
    @property = Property.new
  end


  
  # def calculate_profit_margin
  #   self.profit_percent = self.profit_margin / self.fix_costs
  # end
  # helper_method :calculate_profit_percent #needed if accessed by other views and not just controllers
 
  # POST /properties
  # POST /properties.json

  def create
    @property = Property.new(property_params)
    @property.profit_margin = @property.calculate_profit_margin
    @property.profit_percent = @property.calculate_profit_percent

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def current_property
      @current_property ||= Property.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_property #needed if accessed by other views and not just controllers


  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    if @property.update(property_params)
      redirect_to properties_path
    # else
    #   render :edit
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:address, :list_price, :sale_price, :fix_costs, :time_held, :profit_margin, :profit_percent, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    u = User.find_by(username: params[:unicorn][:username])

    if u && u.authenticate(params[:unicorn][:password])
      session[:user_id] = u.id.to_s #guarnatees session[:user_id] will always be a string of the user's id
      redirect_to properties_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation, :property_id))

    if @user.save
      redirect_to properties_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<div class="container">
  <div class="row"> 
    <div class="jumbotron" class="center-text">
      <div "jumbo-inline">
        <%= image_tag 'house-icon-06-lg.png', size: '300x300'%><br>
        <h1><%= link_to 'FlipHouse/', calculate_path %></h1>
        <div class="intro-spacing">
          <p>a calculator that shows </p><p>the value of your House </p>
        </div>
      </div>
        <!-- <h1><span><%= link_to 'FlopHouse', calculate_path %></span></h1>  -->
      <div>
        <!-- <h4>put your thing down Flip it and reverse it...</h4> --> 
        <%#= link_to 'Listings', '/full_list', class: "btn"%><br>
        <%= link_to "make money!", calculate_path, class: "btn btn-success" %>
      </div>
    </div>  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>FlipHouse</title>
    <%= favicon_link_tag 'house-icon-06-lg.png' %>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700italic|Gudea:400,700|Ek+Mukta:400,600,800|Fredoka+One|Source+Code+Pro|Quattrocento+Sans:400,700|VT323|Comfortaa|Nova+Square|Roboto:400,100' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
  </head>

  
  <body ng-app>
    <div class="container">
      <!-- | angular test: {{ 6 * 7 }}{{ CalcController.simple }} -->

        <% if current_user %>
          <div class="pull-left">
            <%= link_to 'Flip a House', root_path %> |
            <%= link_to "Your Flips", properties_path %> |
            <%= link_to 'Full Flips', '/full_list' %> |
            <%= link_to "Flip again", calculate_path %>
          </div> 
          <div class="pull-right">
              Logged in: <%= current_user.username %> | <%= link_to 'Logout', logout_path %> 

          </div>
        <% else %>
          <div class="pull-left">
            <%= link_to 'Flip a House', root_path %> |
            <%= link_to "Flip List", '/full_list' %>
          </div>
          <div class="pull-right">         
              <%= link_to 'Login', login_path %> | <%= link_to 'Sign up', signup_path %> 
          </div>
        <% end %>
    </div>
    
            <!-- div container wraps all text -->
    <%= yield %>
  <div class="container">
    <footer>
      <%= render 'partials/my_footer' %>
    </footer>  
  </div>
  </body>
 
</html>

app/views/partials/_edit_form.html.erb
<div class="text-center">
  <%= form_for(@property) do |f| %>
    <% if @property.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

        <ul>
        <% @property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :list_price %><br>
      <%= f.number_field :list_price %>
    </div>
    <div class="field">
      <%= f.label :sale_price %><br>
      <%= f.number_field :sale_price %>
    </div>
    <div class="field">
        <%= f.label :fix_costs %><br>
        <%= f.number_field :fix_costs %>
    </div>
    <div class="field">
      <%= f.label "Months held" %><br>
      <%= f.number_field :time_held %>
    </div>

    <br>
    <div class="actions">
      <%= f.submit "ReCalculate Flip"%>
    </div> 
  <% end %>
</div>

app/views/partials/_my_footer.html.erb
<div class="footer">  
  <ul class="footnote">
    <li class="footnote" "pull-left"><a href="https://github.com/AlexMasonAM/project02-WDI-DTLA01" class="footnote" target="_blank">GITHUB |</a></li>
    <li class="footnote" "pull-left"><a href="https://www.linkedin.com/profile/view?id=27932365" class="footnote" target="_blank">LINKED-IN |</a></li>
    <li class="footnote" "pull-left"><a href="https://twitter.com/AlexMasonAM" class="footnote" target="_blank">TWITTER |</a></li>
    <li class="footnote" "pull-right"><a href="https://alexmmason.com" class="footnote" target="_blank">created by [a.mason] |</a></li>
    <li class="footnote" "pull-right"><a href="https://generalassemb.ly/education/web-development-immersive" class="footnote" target="_blank">powered with [General Assembly DTLA-WDI-01]</a></li>
  </ul>
</div>

app/views/properties/_d3result.html.erb
<script>

var width = 600;
var height = 300;
var centerX = 75;
var centerY = 75;

var holder = d3.select("body")
      .append("svg")
      .attr("width", width)    
      .attr("height", height); 


// draw the element
holder.append("rect")
  .style("fill", "grey")
  .style("stroke", "black")
  .style("stroke-width", "2px")
  .attr("x1", 0)
  .attr("y1", 0)
  .attr("width", "175")
  .attr("height","175")
  .attr("rect-anchor", "middle")
  .attr("transform", "translate(225,75) rotate(0)")
  ;

// //polyline element
//   holder.append("polyline")
//   .style("fill", "green")
//   .style("stroke", "black")
//   .style("stroke-width", "2px")
//   .attr("points", "175,175, 200,200, 200,225, 150,225, 150,200, 175,175")
//   .attr("transform", "scale(1)")
//   ;


// when the input range changes update value 

//rotate/angle update
d3.select("#nValue").on("input", function() {
  update1(+this.value);
});

//ratio/scale update
d3.select("#nRatio").on("input", function() {
  update2(+this.value);
});

//ratio/scale update
d3.select("#nColor").on("input", function() {
  colorShift(+this.value);
});

// //ratio/scale update
// d3.select("#nColor").on("input", function() {
//   polylineScale(+this.value);
// });


// Initial update value 
update1(0);
update2(0);
colorShift(255000);
// polylineScale(0);


// rotates appended svg
function update1(nValue) {
  // adjust the value
  holder.select("rect") 
    .attr("transform", "translate(150,100) rotate("+nValue+", 75,75)"); 
}

// scales appended svg
// adjust the ratio
function update2(nRatio) {
  if (-1 < nRatio){
  holder.select("rect") 
      .attr("width", "100" * (1 + nRatio))
      .attr("height","100" * (1 + nRatio))
  }
}
//  changes color of appended svg
function colorShift(nColor) {
  var scale = d3.scale.linear()
                    .domain([-100000, 0, 125500, 255000, 1000000])
                    .range(["red", "white", "lime", "green", "black"]);
  holder.select("rect")
    .style("fill", function() { return scale(nColor) })
}
 // scaling polyline svg
// function colorShift(nRatio) {
//   var scale = d3.scale.linear()
//                     .domain([-100000, 0, 125500, 255000, 1000000])
//                     .range(["red", "white", "lime", "green", "black"]);
//   holder.select("rect")
//     .style("fill", function() { return scale(nColor) })
// }
 
</script>

app/views/properties/_form.html.erb
<div class="text-center">
  <%= form_for(@property) do |f| %>
    <% if @property.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

        <ul>
        <% @property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :list_price %><br>
      <%= f.number_field :list_price, { "ng-model" => "listPrice"} %>
    </div>
    <div class="field">
      <%= f.label :sale_price %><br>
      <%= f.number_field :sale_price,{ "ng-model" => "salePrice" } %>
    </div>
    <div class="field">
        <%= f.label :fix_costs %><br>
        <%= f.number_field :fix_costs, { "ng-model" => "fixCosts" } %>
    </div>
    <div class="field">
      <%= f.label "Months held" %><br>
      <%= f.number_field :time_held %>
    </div>
    <div class="actions">
      <%= f.submit "Calculate Flip"%>
    </div> 
  <% end %>
</div>

app/views/properties/_housesvg.html.erb
<div class="row">
<div class="col-md-3"></div>  
<div class="col-md-6">
  <div id="d3-input">
    <p>
      <label for="nValue" 
             style="display: inline-block; width: 240px; text-align: right">
             Angle/FlopHouse = <span id="nValue-value"></span>
      </label>
      <input type="number" min="-720" max="720" step="5" value="0" id="nValue" >
    </p>
    <p>
      <label for="nColor" 
             style="display: inline-block; width: 240px; text-align: right">
             Color/Profit Margin = <span id="nColor-value"></span>
      </label>
      <input type="number" min="-1000000" max="1000000" step="1000" value="0" id="nColor" >
    </p>
    <p>
      <label for="nRatio" 
             style="display: inline-block; width: 240px; text-align: right">
             Ratio/Profit % = <span id="nRatio-value"></span>
      </label>
      <input type="number" min="-10" max="10" step=".01" value="0" id="nRatio" >
    </p>
  </div>
</div>
<div class="col-md-3"></div>
</div>

app/views/properties/_results.html.erb
<div class="text-center" "result-card">
  <%= form_for(@property) do |f| %>
    <% if @property.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

        <ul>
        <% @property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="result-text">
      <h3>$ profit:</h3>
      <label for="nColor">
        $<%= @property.profit_margin %>
        {{ salePrice - listPrice - fixCosts }}
        <span id="nColor-value"></span>  
      </label>
      <input type="number" min="-1000000" max="1000000" step="1000" value="{{ salePrice - listPrice - fixCosts }}" id="nColor" >
      <h3>% profit:</h3>
      <label for="nRatio">
        {{ (salePrice - listPrice - fixCosts) / fixCosts * 100 }}
        <%= @property.profit_percent%>%
      <span id="nRatio-value"></span>  
      </label>
      <input type="number" min="-10" max="10" step=".10" value="-.2" id="nRatio" >
    </div>
  <% end %>
</div>
      
<%#= render 'd3result' %>

app/views/properties/calculate.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-11">  
          <h1>New Property</h1>
          <h4>enter information about a property to calculate its flip potential</h4>
        </div>
    </div>
    <!-- left grid -->
    <div class="row">
      <div class="col-lg-1">
        <!-- space making div -->
      </div>
    <!-- center grid for Property inputs-->

      <div class="col-lg-3">
        <div class="property-card">
          <div class="text-center">
            <h3>New Property</h3>
            </div>
          <%= render 'form' %>
        </div>
      </div>
      
      <!-- right grid for Property output -->
      
        <div class="col-lg-2">
          <div class="house-results-input" "text-center">
            <%= render 'results' %>
          </div>
        </div>
        <div class="col-lg-5">
          <div class="result-card">  
            <%= render 'd3result' %>
            <div class="text-center"> 
              <div class="calc-image"><%= image_tag 'house-icon-08-lg.png', size: '300x300' %></div>
            </div> 
            <%#= button_tag "Calculate Flip"%>
          </div> 
        </div>
        <div class="col-lg-1">
          <!-- space making div -->
        </div>        
    </div>

    <div class="row">
      <div class="col-lg-4">
          <!-- space making div -->
      </div>

      <div class="col-lg-4">
          <!-- space making div -->
      </div>
    </div>

</div>

app/views/properties/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Editing Property</h1>
      <div class="col-lg-4"></div>
      <div class="col-lg-4">
        <div class="property-card">
          <div class="text-center">
            <h3>Edit Property</h3>
          </div>
          <%= render 'partials/edit_form' %>
        </div>
      </div>
      <div class="col-lg-4"></div>
  </div>
</div>
<div class="row"> 
  <div class="col-lg-5"></div>
  <div class="col-md-4"> 
    <%= link_to 'Destroy', @property, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Show', @property %> |
    <%= link_to 'Back', properties_path %>
  </div>
  <div class="col-lg-3"></div>
</div>

app/views/properties/full_list.html.erb
<!-- table format of saved properties -->

<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 class="jumbtron">Listing Properties</h1>

  <table>
    <thead>
      <tr>
        <!-- <th>Address</th> -->
        <th>List price</th>
        <th>Sale price</th>
        <th>Fix costs</th>
        <th>Time held</th>
        <th>Profit $</th>
        <th>Profit %</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @properties.each do |property| %>
        <tr>
          <!-- <td><%= property.address %></td> -->
          <td><%= property.list_price %></td>
          <td><%= property.sale_price %></td>
          <td><%= property.fix_costs %></td>
          <td><%= property.time_held %></td>
          <td><%= property.calculate_profit_margin %></td>
          <td><%= property.calculate_profit_percent %></td>
          <td><%= link_to 'Show', property %></td>
          <!-- remove editablitly from this session and only add 'your Flips' only -->
          <% if current_user %>
          <td><%= link_to 'Edit', edit_property_path(property) %></td>
          <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
          <% end %> 
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% link_to 'New Property', '/calculate' %>
</div>

app/views/properties/index.html.erb
<div class="container">
  <h1 class="jumbtron">Saved Properties</h1>
  <button class="btn btn-success">sort by newest</button>   <button class="btn btn-success">sort by profit</button>
  <button class="btn btn-success">sort by % profit</button>
  <div class="row">    
    <% @properties.each do |property| %>
      <div class="property-card">
        <div class="text-center">
            <%#= image_tag property.image_url, size:'800x800' %>
            <%= image_tag 'fliphouse-green.png', size: '150x150' %>
            <h2> <%= property.address %> </h2>
            <h2> <%= property.fix_costs %> </h2>
            <h3> <%= property.list_price/property.sale_price %> </h3>
            <%= link_to "House Details!", property %>
        </div>
      </div>
    <% end %>  
  <%#= link_to "Flip a Gain!", calculate_path %>
</div>

app/views/properties/new.html.erb
<div class="container">
  <h1>New Property</h1>
  <h4>enter information to about a property to calculate its flip potential</h4>
  <!-- left grid -->
  <div class="row">
    <div class="col-lg-2">
    </div>
  </div>
  <!-- center grid for Property inputs-->

    <div class="col-lg-4">
      <div class="property-card">
        <div class="text-center">
          <h3>New Property</h3>
        </div>
          <%= render 'form' %>
      </div>
    </div>
  
  <!-- right grid for Property output -->
  
    <div class="col-lg-6">
      <div class="house-start">
      </div> 
    </div>
  </div>
  <%= link_to 'Flip List', properties_path %>
</div>

app/views/properties/p-index.html.erb
<!-- table format of saved properties -->

<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 class="jumbtron">Listing Properties</h1>

  <table>
    <thead>
      <tr>
        <th>Address</th>
        <th>List price</th>
        <th>Sale price</th>
        <th>Fix costs</th>
        <th>Time held</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @properties.each do |property| %>
        <tr>
          <td><%= property.address %></td>
          <td><%= property.list_price %></td>
          <td><%= property.sale_price %></td>
          <td><%= property.fix_costs %></td>
          <td><%= property.time_held %></td>
          <td><%= link_to 'Show', property %></td>
          <td><%= link_to 'Edit', edit_property_path(property) %></td>
          <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Property', new_property_path %>
</div>

app/views/properties/show.html.erb
<% if current_user %>
  <div class="container">
    <h1><%= current_user.username.capitalize %>'s Property Details</h1>
    <h4>this property has a $<%= @property.calculate_profit_margin %> profit potential</h4>
    <!-- left grid -->
    <div class="row">
      <div class="col-lg-2">
      </div>
    </div>
    <!-- center grid for Property inputs-->

      <div class="col-lg-4">
        <div class="property-card">
          <div class="text-center">
            <p>
              <div class="house-saved">
                <%= image_tag 'fliphouse-green.png', size: '150x150'%>
              </div>
            </p>
            <h3><%= @property.address %></h3>
            <p>zillow link</p><br>
          </div>
          <div class="property-results">
              <h5>
                <strong>Profit:</strong>
                  $<%= @property.profit_margin %>
              </h5>
              <h5>
                <strong>% Profit:</strong>
                <%= @property.profit_percent %>%
              </h5>            
              <h5>
                <strong>List price:</strong>
                <%= @property.list_price %>
              </h5>
              <h5>
                <strong>Sale price:</strong>
                <%= @property.sale_price %>
              </h5>
              <h5>
                <strong>Fix costs:</strong>
                <%= @property.fix_costs %>
              </h5> 
              <h5>
                <strong>Months held:</strong>
                <%= @property.time_held %>
              </h5>
              <small><%= @property.date_published %></small>
          </div>   
        </div>

      </div>
    
    <!-- right grid for Property output -->
    <!-- footer for Property Show output -->
    </div><br> 
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2">  
          <%= link_to 'Flip List', properties_path %>  |
          <%= link_to 'Edit', edit_property_path(@property) %>
        </div>  
        <div class="col-md-9"></div>  
      </div>
  <br>
<% else %>
  <h1>you must be logged in to view Property Details</h1>
  <%= link_to 'Login', login_path %>
  <%= link_to 'Signup', '/signup' %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property_id %><br>
    <%= f.text_field :property_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>  

app/views/users/new.html.erb
<div class="container">
  <div class="property-card">
    <div class="text-center">
      <h1>Join the community!</h1>

      <%= form_for @user do |f| %>
        <p>First Name</p>
        <%= f.text_field :first_name %>
        <p>Last Name</p>
        <%= f.text_field :last_name %>
        <p>Username</p>
        <%= f.text_field :username %>
        <p>Password</p>
        <%= f.password_field :password %>
        <p>Confirm password</p>
        <%= f.password_field :password_confirmation %>
        <br><br><br><br>
        <%= f.submit 'Join!' %>
      <% end %>
    </div>
  </div>
</div>